# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/getting-started/

theme = "blowfish"
# baseURL = "https://your_domain.com/"
baseURL = "/"
defaultContentLanguage = "en"

enableRobotsTXT = true
paginate = 20
summaryLength = 30

# whether to use emoji code - disable due to https://github.com/gohugoio/hugo/issues/4978
enableEmoji = false

buildDrafts = false
buildFuture = false

googleAnalytics = "G-2QMNQX8RNG"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]
