---
# https://github.com/DavidAnson/markdownlint/issues/199
MD025:
  front_matter_title: ""
MD041: false

# Line length - https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md013---line-length
# MD013:
#   code_blocks: false
#   tables: false

MD013: false
