name: gh-pages-build

on:
  workflow_call:
  push:

env:
  # renovate: datasource=github-tags depName=gohugoio/hugo
  HUGO_VERSION: 0.104.3

jobs:
  gh-pages-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}

      - uses: actions/cache@v3
        with:
          path: jekyll-chirpy/vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Prepare public directory
        run: |
          mkdir public
          cp LICENSE README.md public/

      - name: Set BASE_DOMAIN
        id: base_domain
        run: |
          if [[ "${GITHUB_BASE_REF}" = "main" ]]; then
            BASE_DOMAIN="${{ github.event.repository.name }}"
          else
            BASE_DOMAIN="$( echo ${{ github.event.repository.name }} | tr . - ).pages.dev"
          fi
          echo "BASE_DOMAIN=${BASE_DOMAIN}" | tee -a "${GITHUB_OUTPUT}"

      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          jekyll_src: jekyll-chirpy
          build_only: true
          build_dir: ../public
          target_path: jekyll-chirpy
          jekyll_build_options: --baseurl /jekyll-chirpy/

      - name: Build hugo pages
        run: |
          # Change links inside config.toml
          sed -i "s/${{ github.event.repository.name }}/${{ steps.base_domain.outputs.BASE_DOMAIN }}/" config.toml
          hugo --gc --destination public
          cd hugo-blowfish
          hugo --gc --baseURL "https://${{ steps.base_domain.outputs.BASE_DOMAIN }}/hugo-blowfish" --destination ../public/hugo-blowfish
          cd ../hugo-loveit
          hugo --gc --baseURL "https://${{ steps.base_domain.outputs.BASE_DOMAIN }}/hugo-loveit" --destination ../public/hugo-loveit

      # - name: Check broken links
      #   uses: ruzickap/action-my-broken-link-checker@v2
      #   with:
      #     url: https://${{ steps.base_domain.outputs.BASE_DOMAIN }}
      #     pages_path: ./public
      #     cmd_params: '--exclude=(linkedin.com) --buffer-size=8192 --max-connections-per-host=5 --color=always --rate-limit=5 --header="User-Agent:curl/7.54.0" --skip-tls-verification'

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: ${{ github.event.repository.name }}

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        if: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/gh-pages' }}
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          branch: main
          directory: ./public
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          projectName: blog-test-ruzicka-dev
