name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: MegaLinter
        uses: megalinter/megalinter@v6.14.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          CSS_STYLELINT_FILTER_REGEX_EXCLUDE: docosaurus-test/src/
          DISABLE_LINTERS: MARKDOWN_MARKDOWN_LINK_CHECK,SPELL_CSPELL,SPELL_MISSPELL
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HTML_HTMLHINT_FILTER_REGEX_EXCLUDE: /index.html
          JAVASCRIPT_STANDARD_FILTER_REGEX_EXCLUDE: docosaurus-test/
          MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdownlint.yml
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
          YAML_V8R_FILTER_REGEX_EXCLUDE: (^jekyll-chirpy/_config.yml)
